version: '3.1'

services:
  api:
    container_name: 'avito_api_est'
    restart: unless-stopped
    build:
      context: ./back-end
    volumes:
      - ./back-end/:/usr/src/app
      - ./back-end/node_modules:/usr/src/app/node_modules #attemtion si merde supprime ./back-end/node_m
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    logging:
      driver: "none"
  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - 1234:1234
    environment:
      - HOST=0.0.0.0
