version: '3'
services:
  back:
    build: ./
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/back/src:z
      - nodemodules:/app/back/node_modules:z
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    volumes:
      - database:/data/db:z

  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - 1234:1234
    environment:
      - HOST=0.0.0.0

volumes:
  database:
  nodemodules: