version: '3'

services:
  back:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app:z
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    depends_on:
      - mongoDB

  mongoDB:
    image: mongo
    restart: always
    logging:
      driver: none

  adminMongo:
    image: mrvautin/adminmongo
    ports:
      - 1234:1234
    command: >
      sh -c "echo -n '{\"app\":{\"host\":\"0.0.0.0\",\"password\":\"password\",\"port\":1234}}' > ./config/app.json && npm start"
