version: '3.1'

services:
  api:
    container_name: Airborn
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./back-end/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    logging:
      driver: "none"

  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - 1234:1234
    environment:
      - HOST=0.0.0.0
