openapi: "3.0.0"
info:
  description: This is an extended documentation of the REST API of Airborn.
  version: 1.0.0
  title: Airborn Api documentation
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8080'
tags:
  - name: Authentification
    description: All routes concerning authentification
  - name: Profile
    description: All routes concerning the management of profiles
  - name: Flight Plan
    description: All routes concerning the management of flight plans
  - name: Feedback
    description: All routes concerning the feedback
paths:
  /api/auth/login:
    post:
      tags:
        - Authentification
      summary: Login
      description: 'Login if the user exist in the database'
      produces:
        - application/json
      requestBody:
        description: User details required to login
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLog'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseTrue'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseFalse'

  /api/auth/register:
    post:
      tags:
        - Authentification
      summary: Register
      description: 'Register the user in the database'
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        description: User details required to login
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLog'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseTrue'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseFalse'

  /api/auth/forgot-password:
    post:
      tags:
        - Authentification
      summary: Forgot Password
      description: 'Request to retrieve password'
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        description: User details required to login
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/forgot-password'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseTrue'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseFalse'

  /api/auth/change-password:
    post:
      tags:
        - Authentification
      summary: Change password
      description: 'Change password'
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        description: User details required to login
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/changePassword'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseTrue'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseFalse'

  /api/auth/register-google:
      post:
        tags:
          - Authentification
        summary: Register Google
        description: 'Register through google services'
        consumes:
          - application/json
        produces:
          - application/json
      requestBody:
        description: User details required to login
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLog'
        responses:
          '200':
            description: Success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApiResponseTrue'
          '400':
            description: Invalid input
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApiResponseFalse'

  /api/profile/update:
    patch:
      tags:
        - Profile
      summary: Update profile
      description: Update the current user profile
      produces:
        - application/xml
        - application/json
      requestBody:
      parameters:
        - in: body
          theme: body
          description: Created user object
          required: true
          schema:
          $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseTrue'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseFalse'

  /api/profile/changeTheme:
    patch:
      tags:
        - Profile
      summary: Change Themes
      description: Change the current theme
      operationId: createUser
      produces:
        - application/xml
        - application/json
      requestBody:
        description: User targeted by the change
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserName'
      parameters:
        - in: body
          theme: body
          description: Created user object
          required: true
          schema:
          $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseTrue'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseFalse'

  /api/profile/get:
    get:
      tags:
        - Profile
      summary: Get profile
      description: Get the current user profile informations
      operationId: createUser
      produces:
        - application/xml
        - application/json
      requestBody:
        description: User to retrieve
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserName'
      parameters:
        - in: body
          theme: body
          description: Created user object
          required: true
          schema:
          $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseTrue'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseFalse'

  /api/flyplan/get:
    post:
      tags:
        - Flyplan
      summary: Get flyplan
      description: Get flyplan
      operationId: createUser
      produces:
        - application/xml
        - application/json
      requestBody:
        description: User to retrieve
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlyPlan'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseTrue'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseFalse'
  /api/flyplan/remove:
    post:
      tags:
        - Flyplan
      summary: remove flyplan
      description: remove flyplan
      operationId: createUser
      produces:
        - application/xml
        - application/json
      requestBody:
        description: User to retrieve
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/removeFlyplan'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseTrue'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseFalse'
  /api/flyplan/getAll:
    get:
      tags:
        - Flyplan
      summary: get All flyplan
      description: get all flyplan
      operationId: createUser
      produces:
        - application/xml
        - application/json
      requestBody:
        description: User to retrieve
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseTrue'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseFalse'
  /api/flyplan/add:
    post:
      tags:
        - Flyplan
      summary: Post flyplan
      description: post flyplan
      operationId: createUser
      produces:
        - application/xml
        - application/json
      requestBody:
        description: User to retrieve
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlyPlan'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseTrue'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseFalse'
  /api/profile/getTheme:
    get:
      tags:
        - Profile
      summary: Get Theme
      description: Get the current theme
      operationId: createUser
      produces:
        - application/xml
        - application/json
      requestBody:
        description: User to retrieve
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserName'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseTrue'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseFalse'
  /api/profile/uploadAvatar:
    post:
      tags:
        - Profile
      summary: upload avatar image
      description: upload avatar
      operationId: createUser
      produces:
        - application/xml
        - application/json
      requestBody:
        description: User to retrieve
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UploadAvatar'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseTrue'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseFalse'
  /api/plan/taf/get:
    post:
      tags:
        - Flight Plan
      summary: Get TAF Plan
      description: Get the current TAF plan attached to an airport
      produces:
        - application/xml
        - application/json
      requestBody:
        description: Aiport details to find attached plan
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Plan'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseTrue'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseFalse'

  /api/plan/vac/get:
    post:
      tags:
        - Flight Plan
      summary: Get VAC Plan
      description: Get the current VAC plan attached to an airport
      produces:
        - application/xml
        - application/json
      requestBody:
        description: Aiport details to find attached plan
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Plan'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseTrue'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref:
  /api/plan/vac/getAll:
    get:
      tags:
        - Flight Plan
      summary: Get VAC Plan
      description: Get the current VAC plan attached to an airport
      produces:
        - application/xml
        - application/json
      requestBody:
        description: Aiport details to find attached plan
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseTrue'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseFalse'

  /api/plan/notam/get:
    post:
      tags:
        - Get NOTAM
      summary: Get NOTAM Plan
      description: Get the current NOTAM plan attached to an airport
      produces:
        - application/xml
        - application/json
      requestBody:
        description: Aiport details to find attached plan
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Plan'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseTrue'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseFalse'

  /api/feedback/get?UserId:
    get:
      tags:
        - FeedBack
      summary: Get, Post FeedBack
      description: Get and Post Feedback
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseTrue'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseFalse'

  /api/feedback/getAll:
      get:
        tags:
          - FeedBack
        summary: Get, Post FeedBack
        description: Get and Post Feedback
        responses:
          '200':
            description: Success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApiResponseTrue'
          '400':
            description: Invalid input
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApiResponseFalse'
  /api/feedback/post:
      post:
        tags:
          - FeedBack
        summary: Get, Post FeedBack
        description: Get and Post Feedback
        produces:
          - application/xml
          - application/json
        requestBody:
          description: Name and description from FeedBack
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/postFB'
        responses:
          '200':
            description: Success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApiResponseTrue'
          '400':
            description: Invalid input
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApiResponseFalse'
components:
  schemas:
    User:
      properties:
        id:
          type: integer
        name:
          type: string
    ApiResponseForgotten:
      type: object
      properties:
        status:
          type: boolean
          default: true
        message:
          type: string
    ApiResponseReset:
      type: object
      properties:
        status:
          type: boolean
          default: true
        message:
          type: string
    ApiResponseTrue:
      type: object
      properties:
        status:
          type: boolean
          default: true
        message:
          type: string
    ApiResponseFalse:
      type: object
      properties:
        status:
          type: boolean
          default: false
        message:
          type: string
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
    UserLog:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      xml:
        name: User
    forgot-password:
      type: object
      properties:
        email:
          type: string
      xml:
        name: User
    changePassword:
      type: object
      properties:
        username:
          uuid: string
        password:
          type: string
      xml:
        name: User
    UserName:
      type: object
      properties:
        username:
          type: string
      xml:
        name: User
    Plan:
      type: object
      properties:
        airport:
          type: string
    removeFlyplan:
        type: object
        properties:
          remove:
            type: string
    FlyPlan:
      type: object
      properties:
        title:
          type: string
    AddFlyPlan:
      type: object
      properties:
        title:
          type: string
        data:
          type: string
        isPublic:
          type: boolean
    UploadAvatar:
      type: object
      properties:
        avatar:
          type: string
    postFB:
      type: object
      properties:
        title:
          type: string
        message:
          type: string




