version: 2.1
orbs:
  node: circleci/node@volatile
  jira: circleci/jira@1.3.0


#######################################################################


jobs:
  ## web
  builder-web:
    executor: node/default
    steps:
      - checkout
      - run:
          command: |
            npm install
            npm build
          working_directory: ~/project/web

  ## mobile
  builder-mobile:
    executor: node/default
    steps:
      - checkout
      - run:
          command: |
            npm install
            npm build
          working_directory: ~/project/mobile

  ## back
  builder-back:
    executor: node/default
    steps:
      - checkout
      - run:
          command: |
            npm install
            npm build
          working_directory: ~/project/back


#######################################################################


workflows:
  test-building:
    jobs:
      ## web
      - builder-web:
          filters:
            branches:
              only:
                - /web.*/
                - apps
                - main

      ## mobile
      - builder-mobile:
          filters:
            branches:
              only:
                - /mobile.*/
                - apps
                - main

      ## back
      - builder-back:
          filters:
            branches:
              only:
                - /back.*/
                - apps
                - main
