name: Node.js Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Check-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: |
          npm i check-build
          check-build
          echo $?
      - run: npm test
