name: CI

on: [push, pull_request]

env:
  SONAR_PROJECT_KEY: airborn:back #! Never use space
  SONAR_PROJECT_NAME: Back        #! Never use space
  SONAR_PATH_SOURCES: .

jobs:
  Test-Unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Installation of Dependencies
        run: npm install
      - name: Running Test
        run: npm run test_ci

  Build-App:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Installation of Dependencies
        run: npm install

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installation of Dependencies
        run: npm install
      - name: Coding Style
        run: npm run lint
